#include <stdio.h>
int main()
{
  int a,b,r1;
  printf("enter a number = ",a);
  scanf("%d",&a);
  printf("enter a number = ",b);
  scanf("%d",&b);
  printf("sum of number = %d",a+b);
  printf("subtraction of number = %d",a-b);
  printf("multiplication of number = %d",a*b);
  printf("divide of number = %d",a/b);
  printf("modules of number = %d",a%b);
  return 0;
}
